name: Build binaries

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6

      - name: Install musl
        run: sudo apt install -y musl-tools

      - name: Setup build target
        run: rustup target add x86_64-unknown-linux-musl

      - name: Build binary
        run: cargo build --release --locked --target=x86_64-unknown-linux-musl

      - name: Compress binary
        uses: svenstaro/upx-action@v2
        with:
          file: target/x86_64-unknown-linux-musl/release/k8s-psl
          args: --lzma
          strip: true

      - name: Upload binary to release
        uses: ncipollo/release-action@v1
        with:
          artifacts: target/x86_64-unknown-linux-musl/release/k8s-psl
